# Generated by Django 3.2.4 on 2021-06-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0003_alter_crimobservation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimrelationship',
            name='details',
            field=models.JSONField(verbose_name={}),
        ),
    ]
