# Generated by Django 3.1.12 on 2021-06-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0004_alter_crimrelationship_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimrelationship',
            name='derivative_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations_as_derivative', to='crim.crimobservation'),
        ),
        migrations.AddField(
            model_name='crimrelationship',
            name='model_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations_as_model', to='crim.crimobservation'),
        ),
        migrations.AddField(
            model_name='crimrelationship',
            name='musical_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='crimobservation',
            name='details',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='crimobservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crimrelationship',
            name='details',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='crimrelationship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
