# Generated by Django 3.1.12 on 2021-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0005_auto_20210625_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimobservation',
            name='details',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='crimrelationship',
            name='details',
            field=models.JSONField(null=True),
        ),
    ]
