# Generated by Django 3.2.4 on 2021-07-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0007_auto_20210628_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimobservation',
            name='observer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='crimrelationship',
            name='observer',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
