# Generated by Django 3.2.4 on 2021-07-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0008_auto_20210702_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRIMDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_definition', models.JSONField(null=True)),
                ('relationship_definition', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Definition',
                'verbose_name_plural': 'Definitions',
            },
        ),
    ]
