# Generated by Django 3.2.4 on 2021-07-15 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0010_crimobservation_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimrelationship',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definition_for_relationship', to='crim.crimdefinition'),
        ),
    ]
