# Generated by Django 3.1.12 on 2021-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0011_crimrelationship_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimobservation',
            name='ema',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='crimdefinition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crimobservation',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimobservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crimrelationship',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crimrelationship',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
