# Generated by Django 3.1.13 on 2021-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crim', '0012_auto_20211119_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRIMObservation',
            new_name='CJObservation',
        ),
        migrations.RenameModel(
            old_name='CRIMRelationship',
            new_name='CJRelationship',
        ),
        migrations.AlterModelOptions(
            name='cjobservation',
            options={'verbose_name': 'Observation (updated)', 'verbose_name_plural': 'Observations (updated)'},
        ),
    ]
